services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /opt/docker/homepage:/app/config # Make sure your local config directory exists
      - /opt/images:/app/public/images # mount a path to where your images are kept
    env_file:
      - .env
